dailydone_project/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

# The following line is to handle media files during development
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.PublicHome.as_view(), name="public_home"),
    path('private/', views.PrivateHome.as_view(), name='private_home'),
    path('about/', views.About.as_view(), name='about'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('projects/', views.ProjectList.as_view(), name='project_list'),
    path('project/new/', views.ProjectCreate.as_view(), name="project_create"),
    path('projects/<int:pk>/', views.ProjectDetail.as_view(), name='project_detail'),
    path('projects/<int:pk>/update', views.ProjectUpdate.as_view(), name='project_update'),
    path('projects/<int:pk>/delete',views.ProjectDelete.as_view(), name='project_delete'),
    path('projects/<int:pk>/complete', views.ProjectComplete.as_view(), name='project_complete'),
    path('completed_projects/', views.CompletedProjectList.as_view(), name='completed_project_list'),
    path('tasks/', views.TaskList.as_view(), name='task_list'),
    path('tasks/new/', views.TaskCreateWithProjects.as_view(), name='task_create'),
    # add, detail, update and remove task
    path('projects/<int:pk>/tasks/new/', views.TaskCreateWithProject.as_view(), name='project_task_create'),
    path('tasks/<int:pk>/', views.TaskDetail.as_view(), name='task_detail'),
    path('tasks/<int:pk>/update', views.TaskUpdate.as_view(), name='task_update'),
    path('tasks/<int:pk>/delete', views.TaskDelete.as_view(), name='task_delete'),
    path('tasks/complete/', views.TaskCompletedList.as_view(), name='task_complete'),
    # for the tasks in the project detail page 
    path('tasks/<int:pk>/complete', views.TaskCompleteView.as_view(), name='task_complete'),
    # User
    path('accounts/signup/', views.Signup.as_view(), name="signup"),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name='user_profile'),
    path('profile/<int:pk>/update', views.UserProfileViewUpdate.as_view(), name='user_profile_update'),
    path('profile/<int:pk>/delete', views.UserProfileDelete.as_view(), name='user_profile_delete'),

]

main_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Project(models.Model):
    STATUS_CHOICES = [
        ('not_started', 'Not Started'),
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('on_hold', 'On Hold'),
        ('cancelled', 'Cancelled'),
    ]

    IMPORTANCE_CHOICES = [
        ('high', 'High Priority'),
        ('medium', 'Medium Priority'),
        ('low', 'Low Priority'),
    ]

    title = models.CharField(max_length=400)
    description = models.TextField(max_length=4000)
    start_date = models.DateField()
    due_date = models.DateField()
    importance = models.CharField(max_length=100, choices=IMPORTANCE_CHOICES)
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default='pending')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    admin = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    is_completed = models.BooleanField(default=False)
    contributors = models.ManyToManyField(User, related_name='contributed_projects', blank=True)

    def __str__(self):
        return self.title
    
    # Displays the name of admin
    def get_user_display(self):
        return self.admin.username

    # Displays the name of contributors in a project separated by commas
    def get_contributors_display(self):
        return ", ".join([contributor.username for contributor in self.contributors.all()])

    class Meta:
        ordering = ['title']


class Task(models.Model):
    IMPORTANCE_CHOICES = [
        ('high', 'High Priority'),
        ('medium', 'Medium Priority'),
        ('low', 'Low Priority'),
    ]

    title = models.CharField(max_length=3000)
    description = models.TextField(max_length=4000, null=True)
    is_completed = models.BooleanField(default=False)
    importance = models.CharField(max_length=100, choices=IMPORTANCE_CHOICES)
    completion_date = models.DateField(null=True, blank=True)
    due_date = models.DateField(null=True, blank=True) 
    created_at = models.DateTimeField(auto_now_add=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="tasks")
    contributors = models.ManyToManyField(User, related_name='contributed_tasks', blank=True)
    admin = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title
    
    # Displays the name of contributors in a task tables separated by commas
    def get_contributors_display(self):
        return ", ".join([contributor.username for contributor in self.contributors.all()])

    def save(self, *args, **kwargs):
        # Check if in the save method if admin field is not provided when we save an new task. If the 2 condition are reunited we do the next step
        if not self.pk and not self.admin:
            self.admin = self._get_current_user()  # Set the admin field to the current user using Django's built-in authentication method _get_current_user
        super().save(*args, **kwargs)  # Call the original save method to save the task with the updated admin field

    def _get_current_user(self):
        return self.request.user  # Retrieve the currently logged-in user
    
    
class TaskComplete(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    completed_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.task.title
    
    def get_user_display(self):
        return self.task.admin.username
    
    def get_contributors_display(self):
        return ", ".join([contributor.username for contributor in self.task.contributors.all()])
    

class UserProfile(models.Model):
    # We associate it with the user model and as we have some user that are notyet associate we add null=true
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = models.TextField(max_length=4000, blank=True)
    location = models.CharField(max_length=2000, blank=True)
    interests = models.TextField(max_length=4000, blank=True)
    # picture = models.ImageField(upload_to='media', blank=True)
    
    def __str__(self):
        return self.user.username
    
# It's a receiver function that will automatically create a UserProfile when a new User is created
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

# Receiver function that will automatically save the UserProfile instance when the User instance is saved
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()

# Post save signal django notion example
# Part of source: https://studygyaan.com/django/how-to-use-and-create-django-signals

main_app/views.py
from django.contrib.auth import login
# from django.contrib.auth.forms import UserCreationForm
from .forms import UserRegistrationForm, UserForm #import the form for registration as i don't use UserCreationForm form any more as i added more fields to the signup form 


# Auth
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .models import Project, Task, TaskComplete, UserProfile
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.base import TemplateView
from django.views.generic import DetailView, ListView
from django.db.models import Q
from datetime import date, datetime
from django.forms import ModelForm




class PublicHome(TemplateView):
    template_name = "public_home.html"

@method_decorator(login_required, name='dispatch')
class PrivateHome(TemplateView):
    template_name = "private_home.html"

class Signup(View):
    # show a form to fill out
    def get(self, request):
        form = UserRegistrationForm() #I updated this line not UserCreationForm anymore so I remove the import
        context = {"form": form}
        return render(request, "registration/signup.html", context)
    # on form submit, validate the form and login the user.
    def post(self, request):
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("project_list")
        else:
            context = {"form": form}
            return render(request, "registration/signup.html", context)



class About(TemplateView):
    template_name = "about.html"


@method_decorator(login_required, name='dispatch')
class ProjectCreate(CreateView):
    model = Project
    fields = ['title', 'description', 'start_date', 'due_date', 'importance', 'status', 'contributors']
    template_name = "project_create.html"

    def form_valid(self, form):
        form.instance.admin = self.request.user  # logged-in admin(user) to the form
        self.object = form.save()  # I store the newly created Project instance to access its 'pk'
        return redirect('project_task_create', self.object.pk)  # I redirect to the 'project_task_create' view, passing the newly created Project's 'pk'

    def get_success_url(self):
        return reverse('project_detail', kwargs={'pk': self.object.pk})

@method_decorator(login_required, name='dispatch')
class ProjectList(TemplateView):
    template_name = "project_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # to get the query parameter we have to acccess it in the request.GET dictionary object        
        title = self.request.GET.get("title")
        # If a query exists we will filter by title 
        if title != None:
            # .filter is the sql WHERE statement and title__icontains is doing a search for any title that contains the query param and link to the admin who is links to the project and keep only the project that are NOT completed
            context["projects"] = Project.objects.filter(title__icontains=title, admin=self.request.user, is_completed=False)
            # We add a header context that includes the search param
            context["header"] = f"Searching for {title}"
        else:
            context["projects"] = Project.objects.filter(admin=self.request.user, is_completed=False)
            # default header for not searching 
            context["header"] = "List Of Projects"
        return context

@method_decorator(login_required, name='dispatch')
class ProjectDetail(DetailView):
    model = Project  
    template_name = "project_detail.html"  

    # Override the get_context_data method
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  
        context['tasks'] = Task.objects.filter(project=self.object, is_completed=False)
        return context

    def post(self, request, *args, **kwargs):
        project = self.get_object()  # Get the Project instance
        task_ids = request.POST.getlist('task_ids[]')  # Get the task IDs from the request POST data
        # Filter tasks that have an ID in task_ids
        print(task_ids) 
        completed_tasks = Task.objects.filter(pk__in=task_ids)
        
        for task in completed_tasks:
            task.is_completed = True  # Mark the task as completed
            task.save()  # Save the changes
            TaskComplete.objects.create(task=task)  # Create a TaskComplete instance for the task
        
        return redirect('project_detail', pk=project.pk)

@method_decorator(login_required, name='dispatch')
class ProjectUpdate(UpdateView):
    model = Project
    fields = ['title', 'description', 'start_date', 'due_date', 'importance', 'status', 'contributors', 'is_completed']
    template_name = "project_update.html"

    def get_success_url(self):
        return reverse('project_detail', kwargs={'pk': self.object.pk})


@method_decorator(login_required, name='dispatch')
class ProjectDelete(DeleteView):
    model = Project
    template_name = "project_delete_confirmation.html"
    success_url = "/projects/"

    # make sure the person that can delete the project is teh one who creates it before the project is deleted. so we see they hav ethe right to do so. When i'ts delete, redirection on the project list page
    def get_queryset(self):
        return self.request.user.projects.all()
    
    def get_success_url(self):
        return reverse('project_list')

# handle the action of marking a project as completed
@method_decorator(login_required, name='dispatch')
class ProjectComplete(View):
    def post(self, request, *args, **kwargs):
        project = Project.objects.get(pk=kwargs['pk'], admin=request.user)
        project.is_completed = True
        project.save()
        return redirect('project_list')

# CompletedProjectList is intended to handle a GET request and display the list of completed projects   
@method_decorator(login_required, name='dispatch')
class CompletedProjectList(TemplateView):
    template_name = "completed_project_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["completed_projects"] = Project.objects.filter(is_completed=True, admin=self.request.user)
        return context


@method_decorator(login_required, name='dispatch')
class TaskList(ListView):
    model = Task
    template_name = 'task_list.html'
    context_object_name = 'tasks'
    ordering = 'due_date'

    # to see task that are not completed yet 'is_completed=False'
    def get_queryset(self):
        return Task.objects.filter(Q(admin=self.request.user) | Q(contributors=self.request.user), is_completed=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['completed_tasks'] = Task.objects.filter(Q(admin=self.request.user) | Q(contributors=self.request.user), is_completed=True)
        return context

    
@method_decorator(login_required, name='dispatch')
class TaskDetail(DetailView):
    model = Task
    template_name = 'task_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task = self.object  

        context['admin'] = task.admin.username
        context['contributors'] = ", ".join([contributor.username for contributor in task.contributors.all()])
        return context
    
    def post(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=kwargs['pk'])
        if 'is_completed' in request.POST:
            task.is_completed = True
            task.save()
        return redirect('task_list')


@method_decorator(login_required, name='dispatch')
class TaskCompletedList(ListView):
    model = Task
    template_name = 'task_completed_list.html'
    context_object_name = 'tasks'  

    # Utilisation of Q objects that allow for complex lookups in Django. Here we check if the logged-in user is either the admin or a contributor with Q object filters filtering tasks that are set as completed. the filter conditions are separated by pipe '|'
    def get_queryset(self):
        return Task.objects.filter(Q(admin=self.request.user) | Q(contributors=self.request.user), is_completed=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['completed_tasks'] = self.get_queryset()
        return context

@method_decorator(login_required, name='dispatch')
class TaskCompleteView(View):
    template_name = "task_complete.html"

    def post(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        task.is_completed = not task.is_completed  

        task.save()
        return redirect('task_list')


# This view is for creating a Task with multiple associated projects
@method_decorator(login_required, name='dispatch')
class TaskCreateWithProjects(CreateView):
    model = Task
    fields = ['title', 'description', 'is_completed', 'importance','project', 'due_date', 'contributors']
    template_name = 'task_create.html'
    success_url = "/tasks/" 

# access to all the projects to pick in the list
    def get_context_data(self, **kwargs):
        context = super().get_context_data( **kwargs)
        context['projects'] = Project.objects.filter(admin=self.request.user)
        return context
    
    def form_valid(self, form):
        task = form.save(commit=False)
        task.admin = self.request.user  # assign the current user as admin automatically
        task.save()
        form.save_m2m()  # necessary to save MToM relationship
        return redirect(self.success_url)

main_app/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About{% endblock %}

{% block content %}
<div class="about-page-container">
    <div class="top-section">
        <h1 class="about-page-title">DailyDone</h1>
        <p class="about-description">
            DailyDone is a streamlined project management tool crafted for efficiency and superb user-experience. Enabling users to <strong style="color: #FA0644;">easily create, track, update, and complete tasks and projects</strong>, it injects simplicity into every step of project management. The platform fosters productivity and team collaboration by providing features for task assignments, timeline creation. With the profile feature, users gain a personalized experience. The dashboard provides an overview of ongoing tasks, upcoming deadlines, and completed achievements, giving users a comprehensive picture of their productivity landscape.
            <br>
            <br>
            Whether managing personal tasks or coordinating team-based projects, DailyDone offers a comprehensive solution to visualize and monitor progress seamlessly. With its user-friendly interface and a wealth of features, it's an optimal choice for anyone seeking a superior approach for project management and task tracking. With DailyDone, we aim to turn every day into a day of accomplishment.
        </p>
    </div>

    <section class="key-features-section">
      <h2 class="section-title">Key Features:</h2>
      <div class="features-list">
          <div class="feature-item">
              <img class="feature-image" src="{% static 'images/user_authentification_img.jpeg' %}" alt="User Authentication picture">
              <div class="feature-content">
                  <h3 class="feature-title">User Authentication</h3>
                  <p class="feature-description">Register, Login, Logout, Create and Edit User Profile</p>
              </div>
          </div>

          <div class="feature-item">
            <img class="feature-image" src="/static/images/Project_Management_img.jpeg" alt="Project Management Icon">
            <div class="feature-content">
              <h3 class="feature-title">Project Management</h3>
              <p class="feature-description">Create, View, Edit, and Delete projects, Set Project's Characteristics, Monitor Project's Status, Assign Admin and Contributors to projects, Mark them as as completed</p>
            </div>
          </div>

          <div class="feature-item">
              <img class="feature-image" src="/static/images/Task_Management_img.jpeg" alt="Task Management Icon">
              <div class="feature-content">
                  <h3 class="feature-title">Task Management</h3>
                  <p class="feature-description">Add, View, Update, and Delete tasks, Set Task's Characteristics within projects, , Monitor Task's Status, Assign Admin and Contributors to tasks, Mark them as as completed</p>
              </div>
          </div>

          <div class="feature-item">
              <img class="feature-image" src="/static/images/Collaboration_img.jpeg" alt="Collaboration Icon">
              <div class="feature-content">
                  <h3 class="feature-title">Collaboration</h3>
                  <p class="feature-description">Assign tasks to specific unique or multiple contributor(s) and invite them to join projects and tasks, display list of Contributors and Admin per project and task</p>
              </div>
          </div>

          <div class="feature-item">
              <img class="feature-image" src="/static/images/user_profile_img.jpeg" alt="User Profile Icon">
              <div class="feature-content">
                  <h3 class="feature-title">User Profile</h3>
                  <p class="feature-description">With our user profiles, each individual can tailor their experience to fit their needs, enhancing productivity and providing a personalized touch to project management</p>
              </div>
          </div>
      </div>
  </section>

  <div class="learn-more-section">
    <a href="{% url 'signup' %}" class="learn-more-button">Learn More</a>
  </div>

  <div class="developer-section">
    <div class="left-side-image">
      <div class="image-wrapper"> 
          <img
              class="image is-128x128 developer-image"
              src="/static/images/pict_Dolores_Crazover.png"
              alt="Dolores Crazover"
          />
      </div>
  </div>
  <h2 class="developer-title">About the Developer</h2>
  <p class="developer-description">
      Dolores openly shares her work and development journey on her <a href="https://github.com/DoloresCode" target="_blank" style="color: #FA0644; font-weight: bold;">GitHub</a> page. She welcomes you to connect with her on <a href="https://www.linkedin.com/in/dolores-crazover/" target="_blank" style="color: #FA0644; font-weight: bold;">LinkedIn</a> to know more about her professional endeavors. For <strong style="color: #FA0644;">Full Stack Software development opportunities</strong>, questions, or if you would like to discuss potential collaborations, please don't hesitate to reach out to Dolores via email <a href="mailto:dcrazover@gmail.com" style="color: #FA0644; font-weight: bold;">here</a>. She looks forward to helping individuals and teams accomplish more every day with DailyDone.
  </p>
</div>
</div>
{% endblock %}

main_app/templates/completed_project_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Completed Projects List{% endblock %}

{% block content %}
    <div class="completed-pjct-container">
        <h1 class="completed-pjct-title">Completed Projects ({{ completed_projects|length }})</h1>

        <a class="completed-pjct-button" href="{% url 'project_list' %}">Go Back to Project List</a>

    {% if completed_projects %}
        <ul class="completed-pjct-list">
            {% for project in completed_projects %}
                <li class="completed-pjct-item">
                    <h2 class="completed-pjct-name">
                        <a href="{% url 'project_detail' project.id %}">{{ project.title }}</a>
                    </h2>
                    <div class="completed-pjct-details">
                        <p class="completed-pjct-date">
                            <strong>Due Date:</strong> {{ project.due_date }}
                        </p>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No completed projects found.</p>
    {% endif %}
    </div>
{% endblock %}

main_app/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="dashboard-container">
        <div class="admin-greeting-dashb">Hello, {{ request.user.username }}</div>

        <div class="tasks-dashb-container">
            <h1 class="dashb-h1">{{ current_date|date:"F j, Y" }}</h1>
            <h2 class="dashb-h2">TASKS</h2>
            <p class="dashb-p total">Total <span>{{ tasks_remaining.count }}</span></p>
            <p class="dashb-p today">Today <span>{{ tasks_today.count }}</span></p>
            <p class="dashb-p upcoming">Upcoming <span>{{ tasks_upcoming.count }}</span></p>
            <a href="{% url 'task_list' %}" class="arrow-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-right-circle" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
            </svg>
            </a>
        </div>

        <div class="project-dashb-container">
            <h2 class="dashb-h2">PROJECTS' LIST</h2>
            <p class="dashb-p total">Total <span>{{ projects_remaining.count }}</span></p>
            <p class="dashb-p today">Today <span>{{ projects_today.count }}</span></p>
            <a href="{% url 'project_list' %}" class="arrow-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-right-circle" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
            </svg>
            </a>
        </div>

        <div class="profile-dashb-container">
            <a href="{% url 'user_profile' request.user.id %}" class="arrow-icon black">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-right-circle" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
            </svg>
            </a>
        </div>
    </div>
{% endblock %}


{% comment %} source icons: https://icons.getbootstrap.com/icons/calendar3/ {% endcomment %}

main_app/templates/project_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Projects List{% endblock %}

{% block content %}
    <div class="project-completed-container">
        <h1 class="title pt-5">{{header}} ({{ projects|length }} To Do)</h1>

        <div class="search-feature">
            <form class="mb-5" method="get">
                <div class="field has-addons">
                    <div class="control">
                        <!--  Our input will search by title of project  -->
                        <input class="input" type="text" name="title" placeholder="title" />
                    </div>
                    <div class="control">
                    <input class="button custom-button-search" type="submit" value="Search" />
                    </div>
                </div>
                <!--  This anchor tag will redirect back to project list without a query param -->
                <a class="button is-dark" href="{% url 'project_list' %}">Clear Search</a>
            </form>
        </div>

        <div class="add-project-btn">
            <a class="button is-dark" href="{% url 'project_create' %}">Add Project</a>
        </div>

        {% comment %} source: forloop.counter for list https://www.w3schools.com/django/django_tags_for.php {% endcomment %}
        {% if projects %}
            <ul class="project-completed-list">
                {% for project in projects %} 
                <li class="project-completed-item">
                    <!-- link for access to project detail page --->
                    <a href="{% url 'project_detail' project.id %}"> 
                    <div class="project-completed-header">
                        <div class="project-completed-number">{{ forloop.counter }}</div>
                        <h2 class="project-completed-name">{{ project.title }}</h2>
                    </div>
                    <div class="project-completed-info">
                        <div class="project-info-line">
                            <div><strong>Admin:</strong> {{ project.get_user_display }}</div>
                            <div><strong>Contributor(s):</strong> {{ project.get_contributors_display }}</div>
                            <div><strong>Importance:</strong> {{ project.get_importance_display }}</div>
                        </div>
                        <div class="project-dates-line">
                            <div><strong>Start Date:</strong> {{ project.start_date }}</div>
                            <div><strong>Due Date:</strong> {{ project.due_date }}</div>
                            <div><strong>Status:</strong> {{ project.get_status_display }}</div>
                        </div>
                    </div>
                    <div class="project-completed-checkbox">
                        {% if not project.is_completed %}
                            <form method="post" action="{% url 'project_complete' project.pk %}">
                                {% csrf_token %}
                                <input type="checkbox" id="is_completed" name="is_completed" onchange="this.form.submit()">
                                <label for="is_completed" style="font-size: 15px;"><strong>Mark as Completed</strong></label>
                            </form>
                        {% endif %}
                </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No projects found.</p>
        {% endif %}
    </div>
{% endblock %}

main_app/templates/task_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Task Detail{% endblock %}

{% block content %}
    <div id="task-detail">
        <h1 class="task-title-detailpg">{{ task.title }}</h1>
        <p><span class="detail-heading">Project:</span> <br> {{ task.project.title }}</p>
        <p><span class="detail-heading">Description:</span> <br> {{ task.description }}</p>
        <p><span class="detail-heading">Admin:</span> <br> {{ admin }}</p>
        <p><span class="detail-heading">Contributor(s):</span> <br> {{ contributors }}</p>

        <form method="post">
            {% csrf_token %}
            <input type="checkbox" name="is_completed" {% if task.is_completed %}checked{% endif %} onchange="this.form.submit()">
            <span class="detail-heading">Completed</span>
        </form>
        
        <p><span class="detail-heading">Level of Importance:</span> <br> {{ task.get_importance_display|title }}</p>
        <p><span class="detail-heading">Due Date:</span> <br> {{ task.due_date }}</p>
        
        <div id="task-actions">
        <a href="{% url 'task_update' task.id %}"><i class="fas fa-edit"></i></a>
        <a href="{% url 'task_delete' task.id %}"><i class="fas fa-trash"></i></a>
        </div>

        <div id="navigation-links">
        <a href="{% url 'task_list' %}">> Back to Tasks</a>
        <a href="{% url 'project_list' %}">> Back to Projects</a>
        </div>
    </div>
{% endblock %}